# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "zyz/centos7-elasticstack"
  # (Un comment below line if you don' t want the latest vagrant box)
  # config.vm.box_check_update = false

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Asia/Shanghai"
  end

  config.vm.network "forwarded_port", guest: 5601, host: 5601

  config.vm.hostname = "elasicstack"

  # (Set disable to false if you wanna enable the folder mounting)
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "./data", "/data", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "elasicstack"
    vb.gui = false
    vb.cpus = 2
    vb.memory = "3072"
    vb.linked_clone = false
    vb.default_nic_type = "virtio"
    vb.customize ['modifyvm', :id, '--vram', '16' ]
    vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all' ]
    vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all' ]
    
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
  
  end

  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = false
    vmware.vmx["numvcpus"] = 2
    vmware.vmx["memsize"] = 3072
    vmware.whitelist_verified = true
    # Workaround to skip the SSH "Connection refused. Retrying..." issue
    vmware.ssh_info_public = true
  end

end
