# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "zyz/centos7"
  config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.hostname = "centos77.localhost"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos77vb"
    vb.gui = false
    vb.cpus = 1
    vb.memory = "512"
    vb.default_nic_type = "virtio"
    vb.customize ['modifyvm', :id, '--vram', '16' ]
    vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all' ]
    vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all' ]
    
    config.vbguest.auto_update = false
  end

  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = false
    vmware.vmx["numvcpus"] = 1
    vmware.vmx["memsize"] = 512
    vmware.whitelist_verified = true
  end

end

